### ISSUE TITLE
Email id Issue with registered User

### ISSUE THREAD

**Issue by 7597208625** [AppGrate/RecyclingSolutions-Issues#38]
It is just a small issue which came up while doing some testing.

Email id is mentioned in company info page of recycler. However, email id is not there in user page. (Please check).
![WhatsApp Image 2020-12-30 at 6 45 09 PM](https://user-images.githubusercontent.com/73227626/103353562-3272c480-4acf-11eb-8b5c-a9144f9d347f.jpeg)
![WhatsApp Image 2020-12-30 at 6 44 59 PM](https://user-images.githubusercontent.com/73227626/103353568-36064b80-4acf-11eb-9b0d-c7da016b898b.jpeg)

**Comment by prashantgithub82** [comment]
**FIXED**

**Comment by 7597208625** [comment]
NOT FIXED. 

Email id is still not there with registered user.

For JB ECOTEX master user is "PUNIT". So email id of Punit will be same as email id of company. And now when Punit add new user he will add email id of new user.

![WhatsApp Image 2021-01-04 at 7 20 56 PM](https://user-images.githubusercontent.com/73227626/103541849-03d75e00-4ec2-11eb-8467-17aa3688821a.jpeg)

**Comment by prashantgithub82** [comment]
This issue is already fixed. So when you create new record, there won't be any issue but for existing records you have to manually update.
